### ISSUE TITLE
Bug: CompactSeedQR not scanning

### ISSUE THREAD

**Issue by seedhammer** [sparrowwallet/drongo#14]
The top QR can't scan in Sparrow 1.7.8 (presumably because of the zbar upgrade):

<img width="363" alt="image" src="https://github.com/sparrowwallet/drongo/assets/93251679/76fa2ace-701c-49e9-bba9-9968a0f74ff8">

Error:

<img width="363" alt="image" src="https://github.com/sparrowwallet/drongo/assets/93251679/78cebe50-eefe-43ae-9b16-fe99af8bd09a">

**Comment by craigraw** [comment]
Thanks for the bug report, fixed in d7b97c9 and https://github.com/sparrowwallet/sparrow/commit/4b6a03ef564044bda9f92cdf4bff886f1b8a90fb. The workaround for v1.7.8 is to disable zbar by setting the config variable `useZbar` to `false` in the config file (close Sparrow first).

Side note: This issue highlights a serious weakness of CompactSeedQR. The raw bytes returned from zbar (returned from `Symbol.getDataBytes()` in the JNI interface) differ considerably from the raw bytes returned from zxing (returned from `Result.getRawBytes()`). It is clear that the raw bytes returned from QR scanning libraries are poorly defined, and are a poor foundation to base a standard on. For example, the `41 0` or `42 0` header bytes defined in the [specification](https://github.com/SeedSigner/seedsigner/tree/1842c73be9452dccc4bd7094fc521b0e9560567d/docs/seed_qr#recoverability) are not returned at all by zbar. For this reason I cannot recommend this standard going forward.

**Comment by seedhammer** [comment]
> Side note: This issue highlights a serious weakness of CompactSeedQR. The raw bytes returned from zbar (returned from `Symbol.getDataBytes()` in the JNI interface) differ considerably from the raw bytes returned from zxing (returned from `Result.getRawBytes()`). It is clear that the raw bytes returned from QR scanning libraries are poorly defined, and are a poor foundation to base a standard on. For example, the `41 0` or `42 0` header bytes defined in the [specification](https://github.com/SeedSigner/seedsigner/tree/1842c73be9452dccc4bd7094fc521b0e9560567d/docs/seed_qr#recoverability) are not returned at all by zbar. For this reason I cannot recommend this standard going forward.

I believe this analysis is a misunderstanding. Rather, zxing is doing a layer violation by exposing (irrelevant) data tied to the QR standard. See https://github.com/SeedSigner/seedsigner/pull/412 for a proposed clarification to the specification. 

ZBar, in contrast, does the right thing by returning just the decoded payload, nothing else. One example is the [high error correction level](https://github.com/sparrowwallet/sparrow/issues/954) changing decoded data when using zxing. In contrast, ZBar returns the same decoded payload regardless of error correction level.

**Comment by craigraw** [comment]
I would hardly call it a misunderstanding. If a standard specification for something as important as a seed must delve into the details of implementation of various QR reading libraries (and there are many more than zbar and zxing) then clearly something is amiss. I've done the best I can with Sparrow's implementation, but it doesn't leave me feeling great.

The real issue with this standard (in my opinion) is that it errs too far on the side of reducing data size. To simply take 16 bytes of data and assume it represents entropy for a seed assumes too much from too little. I think it's great that people experiment with different approaches, but I don't think this one is a winner. Contrast against the `ur:crypto-seed` standard which has much better descriptive qualities. Of course every approach has tradeoffs, but I don't like the tradeoffs CompactSeedQR is making. You can of course take a different view, and that's ok.
