### ISSUE TITLE
Potential issue with PSBT deserialization code

### ISSUE THREAD

**Issue by hax0kartik** [sparrowwallet/drongo#24]
Hello, while reading Drongo's src code I have come across a potential issue.

Drongo's [PSBTEntry constructor](https://github.com/sparrowwallet/drongo/blob/master/src/main/java/com/sparrowwallet/drongo/psbt/PSBTEntry.java#L42) is incorrectly implemented as it assumes the `keyType` to be a single byte. However, according to [BIP 174](https://github.com/bitcoin/bips/blob/master/bip-0174.mediawiki#specification), `keyType` is a `compactInt`.

Here's the relevant code in [btc core](https://github.com/bitcoin/bitcoin/blob/master/src/psbt.h#L1067-L1068).

**Comment by craigraw** [comment]
Thanks for pointing this out. Fixed in https://github.com/sparrowwallet/drongo/commit/d73d3439f67fe528479b759013529d7049c8cba2. Drongo will now successfully parse `keyType` entries that are larger than a single byte. Since there are no known types that use these large numbers it will simply log a warning, but it is certainly better than failing to parse the PSBT.
